/// Class encapsulating a [MessagesCount] object.
class MessagesCount {
  /// A link to the endpoint to retrieve messages of this conversation.
  String href;

  /// The total number of messages that can be retrieved through pagination for
  /// this conversation.
  int totalCount;

  /// The unique ID generated by the MessageBird platform that identifies latest
  /// message. This field is only sent for conversation start.
  String lastMessageId;

  /// Constructor.
  MessagesCount(this.href, this.totalCount, this.lastMessageId);

  /// Get a json object representing the [MessagesCount]
  Map<String, dynamic> toJson() => {
        'href': href,
        'totalCount': totalCount.toString(),
        'lastMessageId': lastMessageId
      };

  /// Construct a [MessagesCount] object from a [json] object.
  factory MessagesCount.fromJson(Map<String, dynamic> json) => (json == null)
      ? null
      : MessagesCount(json['href'].toString(), int.parse(json['totalCount']),
          json['lastMessageId'].toString());
}
