import 'dart:convert';

import '../../util.dart';

/// Class encapsulating a [MessagesCount] object.
class MessagesCount {
  /// A link to the endpoint to retrieve messages of this conversation.
  final String href;

  /// The total number of messages that can be retrieved through pagination for
  /// this conversation.
  final int totalCount;

  /// The unique ID generated by the MessageBird platform that identifies latest
  /// message. This field is only sent for conversation start.
  final String lastMessageId;

  /// Constructor.
  const MessagesCount({
    this.href,
    this.totalCount,
    this.lastMessageId,
  });

  /// Construct a [MessagesCount] object from a json [String].
  factory MessagesCount.fromJson(String source) =>
      MessagesCount.fromMap((json.decode(source)['data'] != null)
          ? json.decode(source)['data'][0]
          : json.decode(source));

  /// Construct a [MessagesCount] object from a [Map].
  factory MessagesCount.fromMap(Map<String, dynamic> map) => map == null
      ? null
      : MessagesCount(
          href: map['href'],
          totalCount: parseInt(map['totalCount']),
          lastMessageId: map['lastMessageId'],
        );

  /// Get a json [String] representing the [MessagesCount].
  String toJson() => json.encode(toMap());

  /// Convert this object to a [Map].
  Map<String, dynamic> toMap() => {
        'href': href,
        'totalCount': totalCount,
        'lastMessageId': lastMessageId,
      };
}
